### ISSUE TITLE
Issue with -go_constants and signed numbers

### ISSUE THREAD

**Issue by mtratsiuk** [chrusty/openapi2jsonschema#16]
Having swagger definition like:
```
  LatLong:
    type: object
    description: "Specifies a geographic..."
    required:
      - latitude
      - longitude
    properties:
      latitude:
        type: number
        format: double
        maximum: 90.0
        minimum: -90.0
      longitude:
        format: double
        type: number
        maximum: 180.0
        minimum: -180.0
```

I am getting this kind of go constant (please notice - numbers lost their sign information):
```go
const LatLong string = `{
    "$schema": "http://jsonschema.org/draft04/schema#",
    "required": [
        "latitude",
        "longitude"
    ],
    "properties": {
        "latitude": {
            "maximum": 90,
            "minimum": 90,
            "additionalProperties": false,
            "type": "number",
            "format": "double"
        },
        "longitude": {
            "maximum": 180,
            "minimum": 180,
            "additionalProperties": false,
            "type": "number",
            "format": "double"
        }
    },
    "additionalProperties": false,
    "type": "object",
    "description": "Specifies a geographic..."
}`
```

It seems like all the hyphens are removed here - https://github.com/chrusty/openapi2jsonschema/blob/master/internal/schemaconverter/filewriter/writer.go#L61
